### ISSUE TITLE
Memory question

### ISSUE THREAD

**Issue by HeliosZhao** [W-zx-Y/DANNet#3]
Thanks for your code!

As you said in the paper, you implement the code on a single GTX 2080TI GPU, but I encounter the out of memory error when training on a single GTX 2080TI GPU. What is the exact memory space you use?

I encounter the `ModuleNotFoundError: No module named 'joint_transforms'`  [here](https://github.com/W-zx-Y/DANNet/blob/dbd7a937bddf990a8890f1b9b855caf76a445454/dataset/transforms/__init__.py#L1). I think you could change the code to:

```
from . import joint_transforms as joint_transforms
from . import joint_transforms2 as joint_transforms2
from . import transforms as extended_transforms
```

**Comment by W-zx-Y** [comment]
Hi @HeliosZhao,

Thank you for your interest in our work.

I run the code on my computer and there's no memory issue. The following screenshot shows the memory taken on a single GTX 2080TI.
![image](https://user-images.githubusercontent.com/75738803/121705790-00648600-caa3-11eb-99f5-6dba52e3aea3.png)

And for the ModuleNotFoundError might be caused by the python versions.

**Comment by ygjwd12345** [comment]
![image](https://user-images.githubusercontent.com/32895754/123326470-91bf0800-d539-11eb-82c9-0e1acdc950c9.png)
I also face the same problem in xp.

**Comment by xiaomanZ613** [comment]
Thanks for your code!
I added code to your code base, but I encounter the out of memory error when training on two GTX 2080TI GPU. it only shows training on a single GTX 2080TI GPU, can't use two GTX 2080TI Gpus at the same time.
thanks for your help!
