### ISSUE TITLE
pretrained cycleGAN model of Cityscapes→DZ-night

### ISSUE THREAD

**Issue by lmjieSCU** [W-zx-Y/DANNet#9]
Can you provide the pretrained cycleGAN model of Cityscapes→DZ-night?
I'd like to reproduce some results.
Thank you!

**Comment by W-zx-Y** [comment]
Thank you for your interest in our work.
In this paper, we didn't use the CycleGAN. The pre-trained model that you mentioned might be from [MGCDA](https://github.com/sakaridis/MGCDA) which is based on curriculum learning.
Their paper: https://arxiv.org/pdf/2005.14553.pdf

**Comment by lmjieSCU** [comment]
Thank you for your reply.
What I want is the pre-trained model that converted day image to night, or the synthetic nighttime images of cityscapes0>DZ-night.
Could you share it？
Thanks very much.

**Comment by W-zx-Y** [comment]
Our method uses the day-night image pairs (aligned by GPS recording) from Dark-Zurich. The input daytime images and nighttime images of our network are real. We don't have the step to convert the day image to its night version using any pre-trained model.

**Comment by lmjieSCU** [comment]
Oh I'm sorry for my wrong expression.
The synthetic nighttime images is appear in the Comparison.
![%W4 G{MTUG3V%P$9OUWOGX4](https://user-images.githubusercontent.com/71051781/140846960-1c13736e-a9a2-4db8-a80e-6d6b7500b08e.png)

**Comment by W-zx-Y** [comment]
I think I got your point. The AdaptSegNet, ADVENT, and BDL are the domain adaptation approaches that also do not have the image translation stage. The mIoU performance of those lines is borrowed from the paper GCMA[33].

Cityscapes->DZ-night in the table means the adaptation instead of translation (no synthetic image involved). You can use Adaptsegnet and treat Cityscapes as the source and DZ-night as the target to get that results.

**Comment by lmjieSCU** [comment]
Thank for your reply again.
I got it!
